name: MapleAdmin
version: '${project.version}'
main: com.lyttldev.mapleadmin.MapleAdmin
api-version: '1.20'
depend: [LuckPerms]
commands:
  staff:
    usage: /staff
    description: MapleAdmin command
