name: LyttleAdmin
version: '${projectVersion}'
main: com.lyttldev.lyttleadmin.LyttleAdmin
api-version: '1.21'
depend: [LuckPerms]
commands:
  staff:
    usage: /staff
    description: LyttleAdmin command
    permission: lyttleadmin.staff

  lyttleadmin:
    usage: /lyttleadmin [reload]
    description: Shows plugin version and reload config files
    permission: lyttleadmin.staff