name: LyttleAdmin
version: '${projectVersion}'
main: com.lyttldev.lyttleadmin.LyttleAdmin
api-version: '1.20'
depend: [LuckPerms]
commands:
  staff:
    usage: /staff
    description: LyttleAdmin command
